// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjN8EK_iVQMDVWlKhHBeHl6GciAtO65fg',
    appId: '1:532372823119:web:6fedcdc03e5882af9b5e3a',
    messagingSenderId: '532372823119',
    projectId: 'notes-jpk',
    authDomain: 'notes-jpk.firebaseapp.com',
    storageBucket: 'notes-jpk.appspot.com',
    measurementId: 'G-J17GMVQ5Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDxlJfkUsY4i4qYUz8QbldB6AfYtKNHb4',
    appId: '1:532372823119:android:e9cf5ed9a8ff22919b5e3a',
    messagingSenderId: '532372823119',
    projectId: 'notes-jpk',
    storageBucket: 'notes-jpk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2iGygkSv1egUTlx1GJwyj_6OzcN-RlVE',
    appId: '1:532372823119:ios:1c170a4ca49d7c6c9b5e3a',
    messagingSenderId: '532372823119',
    projectId: 'notes-jpk',
    storageBucket: 'notes-jpk.appspot.com',
    iosBundleId: 'jp.kalanithi.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2iGygkSv1egUTlx1GJwyj_6OzcN-RlVE',
    appId: '1:532372823119:ios:604cb87047d663e69b5e3a',
    messagingSenderId: '532372823119',
    projectId: 'notes-jpk',
    storageBucket: 'notes-jpk.appspot.com',
    iosBundleId: 'jp.kalanithi.notes.RunnerTests',
  );
}
